### ISSUE TITLE
BiLSTM不应该是拼接隐藏状态吗？

### ISSUE THREAD

**Issue by gongel** [albertwy/BiLSTM#1]
貌似你拼接的是输出

**Comment by eedalong** [comment]
> 貌似你拼接的是输出
做情感分类最后输出的状态来encode整个句子的内容

**Comment by eedalong** [comment]
@gongel  他做情感分类， 所以用最后的输出来encode整个句子的内容的

**Comment by gongel** [comment]
@eedalong 嗯嗯，感谢

**Comment by Sry2016** [comment]
为啥要拼接啊，不是输出本来已经拼接好了吗？
